import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTypescript,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `prisma generate`; not ours to lint.
    "src/generated/**",
    // Apps Script runs in Google's runtime with its own globals.
    "scripts/google-sheets/**",
  ]),
]);

export default eslintConfig;
